server:
  port: 5555

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wpsports
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    hikari:
      schema:
        classpath: data.sql
    initialization-mode: always

  jpa:
    hibernate:
      #프로그램 실행시 db초기화
      ddl-auto: create
    properties:
      hibernate:
        #                show_sql: true
        format_sql: true  #이쁘게 보여주기
    defer-datasource-initialization: true


##  네이버 로그인 설정
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: lcmV4g_oGg3Q5ccJbUK1
#            client-secret: CDBHVUfA6h
#            #{baseUrl}/{action}/oauth2/code/{registrationId}
#            redirect-url: http://localhost:5555/login/oauth2/code/naver)
#            authorization-grant-type: authorization_code
#            scope: name,email
#            client-name: Naver
#        provider:
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response


JPA 로깅 설정
logging.level:
  org.hibernate.SQL: debug #디버그 레벨로 쿼리 출력
  #  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type: trace #파라미터 보여주기




##geno_home_setting
#server:
#  port: 5555
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wpsports?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    hikari:
#      schema:
#        classpath: data.sql
#    initialization-mode: always
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #                show_sql: true
#        format_sql: true  #이쁘게 보여주기
#    defer-datasource-initialization: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: lcmV4g_oGg3Q5ccJbUK1
#            client-secret: CDBHVUfA6h
#            #{baseUrl}/{action}/oauth2/code/{registrationId}
#            redirect-url: http://localhost:5555/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name,email
#            client-name: Naver
#        provider:
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response
#
#
##JPA 로깅 설정
#logging.level:
#  org.hibernate.SQL: debug #디버그 레벨로 쿼리 출력
#  #  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  org.hibernate.type: trace #파라미터 보여주기